# The telltale sign for this kind of challenge is an enormously large e value.
import owiener
from Crypto.Util.number import long_to_bytes

# --------Data--------#

N = 57943633422408910766980241361132519162403952691415709759392934427490323810750264103238493807674553361979252442333306181382039286845354712473425876485194611445198537800874813383490807803163326133264316993814570886658642386428632271248805891685931306937129071044261781790593910530222318248873160853537415283931
e = 56619157150857917136673969042398516495789214506002660571705572847543835157772103501910304870258671107650213223883386827832141956928025461253405399741332330328953813619510308059965148770521518915437569643243847679471839940768778419573954134325135976091221294391748801737740936012671930771024469734436040382795
c = 28161747062244107019386553698760288276804651080816800729082554200917206099206275693106702198132008821710361924573428510685574935788892361463915229659829183385015066532223080674624658745019834065431129575099051350657715431606917740721053199468755078474641062174483511424988726083222437575879327721459787356986

# --------Wiener's attack--------#

d = owiener.attack(e, N)

if d:
    m = pow(c, d, N)
    flag = long_to_bytes(m).decode()
    print(flag)
else:
    print("Wiener's Attack failed.")
